version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_curso
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: curso_db
      MYSQL_USER: user
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


